# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acisStatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamline',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
