# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acisStatus', '0002_beamline_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamline',
            name='storage_ring_order',
            field=models.IntegerField(default=1),
        ),
    ]
